apiVersion: v1
kind: Pod
metadata:
  name: movidius
spec:
  hostNetwork: true
  restartPolicy: OnFailure
  volumes:
  - name: dev
    hostPath:
      path: /dev
      type:
  containers:
  - name: movidius
    image: movidius:latest 
    command: ["python3"]
    args: ["/opt/ncs_service/ncs_service.py"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev
      mountPath: /dev
