# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import scoring_pb2 as scoring__pb2


class ModelStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Classify = channel.unary_unary(
        '/Model/Classify',
        request_serializer=scoring__pb2.Image.SerializeToString,
        response_deserializer=scoring__pb2.ClassDistribution.FromString,
        )


class ModelServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Classify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ModelServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Classify': grpc.unary_unary_rpc_method_handler(
          servicer.Classify,
          request_deserializer=scoring__pb2.Image.FromString,
          response_serializer=scoring__pb2.ClassDistribution.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Model', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))

