# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scoring.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scoring.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rscoring.proto\"\x18\n\x05Image\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"t\n\x11\x43lassDistribution\x12\x33\n\x0c\x64istribution\x18\x01 \x03(\x0b\x32\x1d.ClassDistribution.ClassScore\x1a*\n\nClassScore\x12\r\n\x05klass\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32\x31\n\x05Model\x12(\n\x08\x43lassify\x12\x06.Image\x1a\x12.ClassDistribution\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='Image.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=41,
)


_CLASSDISTRIBUTION_CLASSSCORE = _descriptor.Descriptor(
  name='ClassScore',
  full_name='ClassDistribution.ClassScore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='klass', full_name='ClassDistribution.ClassScore.klass', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='ClassDistribution.ClassScore.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=159,
)

_CLASSDISTRIBUTION = _descriptor.Descriptor(
  name='ClassDistribution',
  full_name='ClassDistribution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distribution', full_name='ClassDistribution.distribution', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CLASSDISTRIBUTION_CLASSSCORE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=159,
)

_CLASSDISTRIBUTION_CLASSSCORE.containing_type = _CLASSDISTRIBUTION
_CLASSDISTRIBUTION.fields_by_name['distribution'].message_type = _CLASSDISTRIBUTION_CLASSSCORE
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['ClassDistribution'] = _CLASSDISTRIBUTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'scoring_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  ))
_sym_db.RegisterMessage(Image)

ClassDistribution = _reflection.GeneratedProtocolMessageType('ClassDistribution', (_message.Message,), dict(

  ClassScore = _reflection.GeneratedProtocolMessageType('ClassScore', (_message.Message,), dict(
    DESCRIPTOR = _CLASSDISTRIBUTION_CLASSSCORE,
    __module__ = 'scoring_pb2'
    # @@protoc_insertion_point(class_scope:ClassDistribution.ClassScore)
    ))
  ,
  DESCRIPTOR = _CLASSDISTRIBUTION,
  __module__ = 'scoring_pb2'
  # @@protoc_insertion_point(class_scope:ClassDistribution)
  ))
_sym_db.RegisterMessage(ClassDistribution)
_sym_db.RegisterMessage(ClassDistribution.ClassScore)



_MODEL = _descriptor.ServiceDescriptor(
  name='Model',
  full_name='Model',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=161,
  serialized_end=210,
  methods=[
  _descriptor.MethodDescriptor(
    name='Classify',
    full_name='Model.Classify',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_CLASSDISTRIBUTION,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODEL)

DESCRIPTOR.services_by_name['Model'] = _MODEL

# @@protoc_insertion_point(module_scope)

